In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

from keras.models import Sequential
from keras.layers import Dense , LSTM , Dropout

Using TensorFlow backend.


In [2]:
dataset = pd.read_csv('Google_Stock_Price_Train.csv')
dataset_test = pd.read_csv('Google_Stock_Price_Test.csv')

In [3]:
dataset.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [4]:
dataset.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [5]:
training_data = dataset.iloc[: , 1:2].values
training_data

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [6]:
sc = MinMaxScaler(feature_range = (0 , 1))
scaled_train_data = sc.fit_transform(training_data)
scaled_train_data

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [7]:
X_train = []
y_train = []

for i in range(60 , 1258):
    X_train.append(scaled_train_data[i - 60 : i , 0])
    y_train.append(scaled_train_data[i , 0])
    
    
X_train , y_train = np.array(X_train) , np.array(y_train)

In [8]:
X_train

array([[0.08581368, 0.09701243, 0.09433366, ..., 0.07846566, 0.08034452,
        0.08497656],
       [0.09701243, 0.09433366, 0.09156187, ..., 0.08034452, 0.08497656,
        0.08627874],
       [0.09433366, 0.09156187, 0.07984225, ..., 0.08497656, 0.08627874,
        0.08471612],
       ...,
       [0.92106928, 0.92438053, 0.93048218, ..., 0.95475854, 0.95204256,
        0.95163331],
       [0.92438053, 0.93048218, 0.9299055 , ..., 0.95204256, 0.95163331,
        0.95725128],
       [0.93048218, 0.9299055 , 0.93113327, ..., 0.95163331, 0.95725128,
        0.93796041]])

In [9]:
X_train = np.reshape(X_train , (X_train.shape[0] , X_train.shape[1] , 1))
X_train

array([[[0.08581368],
        [0.09701243],
        [0.09433366],
        ...,
        [0.07846566],
        [0.08034452],
        [0.08497656]],

       [[0.09701243],
        [0.09433366],
        [0.09156187],
        ...,
        [0.08034452],
        [0.08497656],
        [0.08627874]],

       [[0.09433366],
        [0.09156187],
        [0.07984225],
        ...,
        [0.08497656],
        [0.08627874],
        [0.08471612]],

       ...,

       [[0.92106928],
        [0.92438053],
        [0.93048218],
        ...,
        [0.95475854],
        [0.95204256],
        [0.95163331]],

       [[0.92438053],
        [0.93048218],
        [0.9299055 ],
        ...,
        [0.95204256],
        [0.95163331],
        [0.95725128]],

       [[0.93048218],
        [0.9299055 ],
        [0.93113327],
        ...,
        [0.95163331],
        [0.95725128],
        [0.93796041]]])

In [10]:
X_train.shape

(1198, 60, 1)

In [11]:
regressor = Sequential()

regressor.add(LSTM(units = 50 , return_sequences = True , input_shape = (X_train.shape[1] , 1)))
regressor.add(Dropout(0.2))

In [12]:
regressor.add(LSTM(units = 50 , return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50 , return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

In [13]:
regressor.add(Dense(units = 1))

In [14]:
regressor.compile(optimizer = 'adam' , loss = 'mean_squared_error')

In [ ]:
regressor.fit(X_train , y_train , epochs = 15 , batch_size = 32)

Epoch 1/75
1198/1198 [==============================] - 28s 24ms/step - loss: 0.0362
Epoch 2/75
1198/1198 [==============================] - 23s 19ms/step - loss: 0.0070
Epoch 3/75
1198/1198 [==============================] - 21s 18ms/step - loss: 0.0054
Epoch 4/75
1198/1198 [==============================] - 22s 18ms/step - loss: 0.0049
Epoch 5/75
1198/1198 [==============================] - 22s 18ms/step - loss: 0.0049
Epoch 6/75
1198/1198 [==============================] - 21s 17ms/step - loss: 0.0046
Epoch 7/75
1198/1198 [==============================] - 23s 19ms/step - loss: 0.0047
Epoch 8/75
1198/1198 [==============================] - 24s 20ms/step - loss: 0.0044
Epoch 9/75
1198/1198 [==============================] - 22s 18ms/step - loss: 0.0042
Epoch 10/75
1198/1198 [==============================] - 22s 18ms/step - loss: 0.0041
Epoch 11/75
1198/1198 [==============================] - 22s 19ms/step - loss: 0.0040
Epoch 12/75
1198/1198 [==============================] - 21s 18