# Data Preprocessing

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score , confusion_matrix
_CURRENT_SCRATCH_GRAPH = None

#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, Dropout

In [2]:
# Importing the dataset
dataset = pd.read_csv('G:\Software\Machine learning\Datasets\Deep learning\Churn_Modelling.csv')

In [3]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
#spliting the dataset
x = dataset.iloc[:, 3:12].values
y = dataset.iloc[:, 13].values

In [6]:
x.shape

(10000, 9)

In [7]:
y.shape

(10000,)

## Encoding categorical data

In [8]:
labelencoder_X = LabelEncoder()
x[:, 1] = labelencoder_X.fit_transform(x[:, 1])

In [9]:
x

array([[619, 0, 'Female', ..., 1, 1, 1],
       [608, 2, 'Female', ..., 1, 0, 1],
       [502, 0, 'Female', ..., 3, 1, 0],
       ...,
       [709, 0, 'Female', ..., 1, 0, 1],
       [772, 1, 'Male', ..., 2, 1, 0],
       [792, 0, 'Female', ..., 1, 1, 0]], dtype=object)

In [10]:
labelencoder_X_1 = LabelEncoder()
x[:, 2] = labelencoder_X_1.fit_transform(x[:, 2])

In [11]:
x

array([[619, 0, 0, ..., 1, 1, 1],
       [608, 2, 0, ..., 1, 0, 1],
       [502, 0, 0, ..., 3, 1, 0],
       ...,
       [709, 0, 0, ..., 1, 0, 1],
       [772, 1, 1, ..., 2, 1, 0],
       [792, 0, 0, ..., 1, 1, 0]], dtype=object)

In [12]:
onehotencoder = OneHotEncoder(categorical_features = [1])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
x

array([[1., 0., 0., ..., 1., 1., 1.],
       [0., 0., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 3., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 2., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [14]:
x[:,1:]

array([[  0.,   0., 619., ...,   1.,   1.,   1.],
       [  0.,   1., 608., ...,   1.,   0.,   1.],
       [  0.,   0., 502., ...,   3.,   1.,   0.],
       ...,
       [  0.,   0., 709., ...,   1.,   0.,   1.],
       [  1.,   0., 772., ...,   2.,   1.,   0.],
       [  0.,   0., 792., ...,   1.,   1.,   0.]])

In [15]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [16]:
X_train

array([[0., 1., 0., ..., 3., 0., 0.],
       [1., 0., 0., ..., 2., 1., 0.],
       [0., 0., 1., ..., 2., 1., 1.],
       ...,
       [1., 0., 0., ..., 2., 1., 0.],
       [0., 0., 1., ..., 2., 1., 1.],
       [0., 1., 0., ..., 1., 1., 0.]])

In [17]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
X_train

array([[-1.01558815,  1.76021608, -0.57468161, ...,  2.53503394,
        -1.55362351, -1.03446007],
       [ 0.98465111, -0.56811207, -0.57468161, ...,  0.80424154,
         0.64365658, -1.03446007],
       [-1.01558815, -0.56811207,  1.74009395, ...,  0.80424154,
         0.64365658,  0.96668786],
       ...,
       [ 0.98465111, -0.56811207, -0.57468161, ...,  0.80424154,
         0.64365658, -1.03446007],
       [-1.01558815, -0.56811207,  1.74009395, ...,  0.80424154,
         0.64365658,  0.96668786],
       [-1.01558815,  1.76021608, -0.57468161, ..., -0.92655087,
         0.64365658, -1.03446007]])

In [19]:
X_test

array([[-1.01558815,  1.76021608, -0.57468161, ..., -0.92655087,
         0.64365658,  0.96668786],
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
         0.64365658, -1.03446007],
       [-1.01558815, -0.56811207,  1.74009395, ..., -0.92655087,
         0.64365658,  0.96668786],
       ...,
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
         0.64365658, -1.03446007],
       [-1.01558815,  1.76021608, -0.57468161, ...,  0.80424154,
         0.64365658, -1.03446007],
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
        -1.55362351, -1.03446007]])

In [20]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


## Initializing the ANN

In [21]:
classifier = Sequential()

In [22]:
# input layer and first hidden layer.
classifier.add(Dense(output_dim = 6 , init = 'uniform' , activation = 'relu' , input_dim = 11))

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [23]:
# Add second hidden layer
classifier.add(Dense(output_dim = 6 , init = 'uniform' , activation = 'relu'))

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [24]:
# Add output layer
classifier.add(Dense(output_dim = 1 , init = 'uniform' , activation = 'sigmoid'))

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [25]:
# Compile the code
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [26]:
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Restrict TensorFlow to only use the fourth GPU
        tf.config.experimental.set_visible_devices(gpus[0], 'GPU')

        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

Physical devices cannot be modified after being initialized


In [27]:
# Fit the ANN with training set
classifier.fit(X_train , y_train , batch_size = 10 , epochs = 50)

Epoch 1/50
7500/7500 [==============================] - 5s 693us/step - loss: 0.4791 - accuracy: 0.7961
Epoch 2/50
7500/7500 [==============================] - 5s 657us/step - loss: 0.4277 - accuracy: 0.7963
Epoch 3/50
7500/7500 [==============================] - 4s 567us/step - loss: 0.4226 - accuracy: 0.7976
Epoch 4/50
7500/7500 [==============================] - 4s 518us/step - loss: 0.4190 - accuracy: 0.8193
Epoch 5/50
7500/7500 [==============================] - 5s 669us/step - loss: 0.4166 - accuracy: 0.8240
Epoch 6/50
7500/7500 [==============================] - 4s 578us/step - loss: 0.4151 - accuracy: 0.8280
Epoch 7/50
7500/7500 [==============================] - 5s 646us/step - loss: 0.4137 - accuracy: 0.8304
Epoch 8/50
7500/7500 [==============================] - 5s 638us/step - loss: 0.4124 - accuracy: 0.8316
Epoch 9/50
7500/7500 [==============================] - 4s 548us/step - loss: 0.4113 - accuracy: 0.8323
Epoch 10/50
7500/7500 [==============================] - 4s 542u

In [28]:
# predicting the result
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [29]:
y_pred[:20]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [30]:
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""


new_prediction = classifier.predict(sc.transform(np.array([[0.0 , 0, 600 , 1 , 40 , 3 , 60000 , 2 , 1 , 1 , 50000]])))
new_prediction = (new_prediction > 0.5)

In [33]:
new_prediction

array([[False]])

In [31]:
ac = accuracy_score(y_test , y_pred)
ac

0.8432

In [32]:
confusion_matrix(y_test , y_pred)

array([[1934,   57],
       [ 335,  174]], dtype=int64)