In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score , confusion_matrix
_CURRENT_SCRATCH_GRAPH = None

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

Using TensorFlow backend.


In [2]:
# Importing the dataset
dataset = pd.read_csv('G:\Software\Machine learning\Datasets\Deep learning\Churn_Modelling.csv')

In [3]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
#spliting the dataset
x = dataset.iloc[:, 3:12].values
y = dataset.iloc[:, 13].values

In [5]:
x.shape

(10000, 9)

In [6]:
y.shape

(10000,)

## Encoding categorical data

In [7]:
labelencoder_X = LabelEncoder()
x[:, 1] = labelencoder_X.fit_transform(x[:, 1])

In [8]:
x

array([[619, 0, 'Female', ..., 1, 1, 1],
       [608, 2, 'Female', ..., 1, 0, 1],
       [502, 0, 'Female', ..., 3, 1, 0],
       ...,
       [709, 0, 'Female', ..., 1, 0, 1],
       [772, 1, 'Male', ..., 2, 1, 0],
       [792, 0, 'Female', ..., 1, 1, 0]], dtype=object)

In [9]:
labelencoder_X_1 = LabelEncoder()
x[:, 2] = labelencoder_X_1.fit_transform(x[:, 2])

In [10]:
x

array([[619, 0, 0, ..., 1, 1, 1],
       [608, 2, 0, ..., 1, 0, 1],
       [502, 0, 0, ..., 3, 1, 0],
       ...,
       [709, 0, 0, ..., 1, 0, 1],
       [772, 1, 1, ..., 2, 1, 0],
       [792, 0, 0, ..., 1, 1, 0]], dtype=object)

In [11]:
onehotencoder = OneHotEncoder(categorical_features = [1])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [12]:
x

array([[1., 0., 0., ..., 1., 1., 1.],
       [0., 0., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 3., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 2., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [13]:
x[:,1:]

array([[  0.,   0., 619., ...,   1.,   1.,   1.],
       [  0.,   1., 608., ...,   1.,   0.,   1.],
       [  0.,   0., 502., ...,   3.,   1.,   0.],
       ...,
       [  0.,   0., 709., ...,   1.,   0.,   1.],
       [  1.,   0., 772., ...,   2.,   1.,   0.],
       [  0.,   0., 792., ...,   1.,   1.,   0.]])

In [14]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [15]:
X_train

array([[0., 1., 0., ..., 3., 0., 0.],
       [1., 0., 0., ..., 2., 1., 0.],
       [0., 0., 1., ..., 2., 1., 1.],
       ...,
       [1., 0., 0., ..., 2., 1., 0.],
       [0., 0., 1., ..., 2., 1., 1.],
       [0., 1., 0., ..., 1., 1., 0.]])

In [16]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_test

array([[-1.01558815,  1.76021608, -0.57468161, ..., -0.92655087,
         0.64365658,  0.96668786],
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
         0.64365658, -1.03446007],
       [-1.01558815, -0.56811207,  1.74009395, ..., -0.92655087,
         0.64365658,  0.96668786],
       ...,
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
         0.64365658, -1.03446007],
       [-1.01558815,  1.76021608, -0.57468161, ...,  0.80424154,
         0.64365658, -1.03446007],
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
        -1.55362351, -1.03446007]])

In [18]:
# Create function for classifier

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [20]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10 , epochs = 100)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)

Epoch 1/100
6750/6750 [==============================] - 5s 765us/step - loss: 0.4961 - accuracy: 0.7970
Epoch 2/100
6750/6750 [==============================] - 5s 685us/step - loss: 0.4284 - accuracy: 0.7975
Epoch 3/100
6750/6750 [==============================] - 4s 560us/step - loss: 0.4237 - accuracy: 0.7975
Epoch 4/100
6750/6750 [==============================] - 4s 556us/step - loss: 0.4195 - accuracy: 0.8021
Epoch 5/100
6750/6750 [==============================] - 4s 555us/step - loss: 0.4168 - accuracy: 0.8230
Epoch 6/100
6750/6750 [==============================] - 4s 557us/step - loss: 0.4152 - accuracy: 0.8270
Epoch 7/100
6750/6750 [==============================] - 4s 564us/step - loss: 0.4138 - accuracy: 0.8279
Epoch 8/100
6750/6750 [==============================] - 4s 567us/step - loss: 0.4129 - accuracy: 0.8305
Epoch 9/100
6750/6750 [==============================] - 4s 561us/step - loss: 0.4118 - accuracy: 0.8319
Epoch 10/100
6750/6750 [==============================]

6750/6750 [==============================] - 3s 498us/step - loss: 0.3989 - accuracy: 0.8338
Epoch 81/100
6750/6750 [==============================] - 3s 491us/step - loss: 0.3989 - accuracy: 0.8366
Epoch 82/100
6750/6750 [==============================] - 3s 491us/step - loss: 0.3990 - accuracy: 0.8351
Epoch 83/100
6750/6750 [==============================] - 3s 491us/step - loss: 0.3990 - accuracy: 0.8359
Epoch 84/100
6750/6750 [==============================] - 3s 493us/step - loss: 0.3992 - accuracy: 0.8363
Epoch 85/100
6750/6750 [==============================] - 3s 495us/step - loss: 0.3996 - accuracy: 0.8344
Epoch 86/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3993 - accuracy: 0.8351
Epoch 87/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3987 - accuracy: 0.8347
Epoch 88/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3994 - accuracy: 0.8354
Epoch 89/100
6750/6750 [==============================] - 3

Epoch 57/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3440 - accuracy: 0.8576
Epoch 58/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3437 - accuracy: 0.8559
Epoch 59/100
6750/6750 [==============================] - 3s 495us/step - loss: 0.3432 - accuracy: 0.8576
Epoch 60/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3401 - accuracy: 0.8593
Epoch 61/100
6750/6750 [==============================] - 3s 495us/step - loss: 0.3435 - accuracy: 0.8532
Epoch 62/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3431 - accuracy: 0.8563
Epoch 63/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3420 - accuracy: 0.8607
Epoch 64/100
6750/6750 [==============================] - 3s 498us/step - loss: 0.3419 - accuracy: 0.8567
Epoch 65/100
6750/6750 [==============================] - 3s 493us/step - loss: 0.3422 - accuracy: 0.8578
Epoch 66/100
6750/6750 [======================

6750/6750 [==============================] - 5s 744us/step - loss: 0.4083 - accuracy: 0.8311
Epoch 30/100
6750/6750 [==============================] - 4s 648us/step - loss: 0.4074 - accuracy: 0.8302
Epoch 31/100
6750/6750 [==============================] - 4s 641us/step - loss: 0.4081 - accuracy: 0.8310
Epoch 32/100
6750/6750 [==============================] - 4s 612us/step - loss: 0.4077 - accuracy: 0.8314
Epoch 33/100
6750/6750 [==============================] - 5s 750us/step - loss: 0.4080 - accuracy: 0.8317
Epoch 34/100
6750/6750 [==============================] - 4s 622us/step - loss: 0.4076 - accuracy: 0.8301
Epoch 35/100
6750/6750 [==============================] - 4s 606us/step - loss: 0.4073 - accuracy: 0.8311
Epoch 36/100
6750/6750 [==============================] - 4s 625us/step - loss: 0.4073 - accuracy: 0.8324
Epoch 37/100
6750/6750 [==============================] - 4s 619us/step - loss: 0.4070 - accuracy: 0.8298
Epoch 38/100
6750/6750 [==============================] - 4

6750/6750 [==============================] - 4s 603us/step - loss: 0.3389 - accuracy: 0.8636
Epoch 82/100
6750/6750 [==============================] - 6s 829us/step - loss: 0.3389 - accuracy: 0.8621
Epoch 83/100
6750/6750 [==============================] - 5s 686us/step - loss: 0.3387 - accuracy: 0.8637
Epoch 84/100
6750/6750 [==============================] - 5s 670us/step - loss: 0.3380 - accuracy: 0.8618
Epoch 85/100
6750/6750 [==============================] - 5s 740us/step - loss: 0.3383 - accuracy: 0.8630
Epoch 86/100
6750/6750 [==============================] - 6s 956us/step - loss: 0.3376 - accuracy: 0.86280s - loss: 0.3394 - ac - ETA: 0s - loss: 0.3397 - accura
Epoch 87/100
6750/6750 [==============================] - 5s 807us/step - loss: 0.3374 - accuracy: 0.8646
Epoch 88/100
6750/6750 [==============================] - 4s 659us/step - loss: 0.3377 - accuracy: 0.8634
Epoch 89/100
6750/6750 [==============================] - 4s 645us/step - loss: 0.3370 - accuracy: 0.8640
Epo

6750/6750 [==============================] - 4s 578us/step - loss: 0.3904 - accuracy: 0.8387
Epoch 79/100
6750/6750 [==============================] - 4s 572us/step - loss: 0.3903 - accuracy: 0.8384
Epoch 80/100
6750/6750 [==============================] - 5s 763us/step - loss: 0.3900 - accuracy: 0.8393
Epoch 81/100
6750/6750 [==============================] - 4s 573us/step - loss: 0.3896 - accuracy: 0.8388
Epoch 82/100
6750/6750 [==============================] - 4s 588us/step - loss: 0.3894 - accuracy: 0.8397
Epoch 83/100
6750/6750 [==============================] - 5s 783us/step - loss: 0.3890 - accuracy: 0.8406
Epoch 84/100
6750/6750 [==============================] - 4s 657us/step - loss: 0.3886 - accuracy: 0.8390
Epoch 85/100
6750/6750 [==============================] - 4s 629us/step - loss: 0.3886 - accuracy: 0.8412
Epoch 86/100
6750/6750 [==============================] - 4s 666us/step - loss: 0.3882 - accuracy: 0.8391
Epoch 87/100
6750/6750 [==============================] - 5

In [21]:
mean = accuracies.mean()
variance = accuracies.std()

In [22]:
mean

0.844133335351944

In [23]:
variance

0.016529562575648117