In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score , confusion_matrix
_CURRENT_SCRATCH_GRAPH = None

import keras
from keras.models import Sequential
from keras.layers import Dense , Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

Using TensorFlow backend.


In [2]:
# Importing the dataset
dataset = pd.read_csv('G:\Software\Machine learning\Datasets\Deep learning\Churn_Modelling.csv')

In [3]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
#spliting the dataset
x = dataset.iloc[:, 3:12].values
y = dataset.iloc[:, 13].values

In [5]:
x.shape

(10000, 9)

In [6]:
y.shape

(10000,)

## Encoding categorical data

In [7]:
labelencoder_X = LabelEncoder()
x[:, 1] = labelencoder_X.fit_transform(x[:, 1])

In [8]:
x

array([[619, 0, 'Female', ..., 1, 1, 1],
       [608, 2, 'Female', ..., 1, 0, 1],
       [502, 0, 'Female', ..., 3, 1, 0],
       ...,
       [709, 0, 'Female', ..., 1, 0, 1],
       [772, 1, 'Male', ..., 2, 1, 0],
       [792, 0, 'Female', ..., 1, 1, 0]], dtype=object)

In [9]:
labelencoder_X_1 = LabelEncoder()
x[:, 2] = labelencoder_X_1.fit_transform(x[:, 2])

In [10]:
x

array([[619, 0, 0, ..., 1, 1, 1],
       [608, 2, 0, ..., 1, 0, 1],
       [502, 0, 0, ..., 3, 1, 0],
       ...,
       [709, 0, 0, ..., 1, 0, 1],
       [772, 1, 1, ..., 2, 1, 0],
       [792, 0, 0, ..., 1, 1, 0]], dtype=object)

In [11]:
onehotencoder = OneHotEncoder(categorical_features = [1])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [12]:
x

array([[1., 0., 0., ..., 1., 1., 1.],
       [0., 0., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 3., 1., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 2., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [13]:
x[:,1:]

array([[  0.,   0., 619., ...,   1.,   1.,   1.],
       [  0.,   1., 608., ...,   1.,   0.,   1.],
       [  0.,   0., 502., ...,   3.,   1.,   0.],
       ...,
       [  0.,   0., 709., ...,   1.,   0.,   1.],
       [  1.,   0., 772., ...,   2.,   1.,   0.],
       [  0.,   0., 792., ...,   1.,   1.,   0.]])

In [14]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [15]:
X_train

array([[0., 1., 0., ..., 3., 0., 0.],
       [1., 0., 0., ..., 2., 1., 0.],
       [0., 0., 1., ..., 2., 1., 1.],
       ...,
       [1., 0., 0., ..., 2., 1., 0.],
       [0., 0., 1., ..., 2., 1., 1.],
       [0., 1., 0., ..., 1., 1., 0.]])

In [16]:
# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_test

array([[-1.01558815,  1.76021608, -0.57468161, ..., -0.92655087,
         0.64365658,  0.96668786],
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
         0.64365658, -1.03446007],
       [-1.01558815, -0.56811207,  1.74009395, ..., -0.92655087,
         0.64365658,  0.96668786],
       ...,
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
         0.64365658, -1.03446007],
       [-1.01558815,  1.76021608, -0.57468161, ...,  0.80424154,
         0.64365658, -1.03446007],
       [ 0.98465111, -0.56811207, -0.57468161, ..., -0.92655087,
        -1.55362351, -1.03446007]])

In [18]:
classifier = Sequential()

In [19]:
# input layer and first hidden layer with dropout
classifier.add(Dense(output_dim = 6 , init = 'uniform' , activation = 'relu' , input_dim = 11))
classifier.add(Dropout(p = 0.1))

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  This is separate from the ipykernel package so we can avoid doing imports until


In [20]:
# input layer and second hidden layer with dropout
classifier.add(Dense(output_dim = 6 , init = 'uniform' , activation = 'relu' , input_dim = 11))
classifier.add(Dropout(p = 0.1))

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  This is separate from the ipykernel package so we can avoid doing imports until


In [26]:
# Create function for classifier

def build_classifier(optimizer = 'adam'):
    classifier = Sequential()
    
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier

In [27]:
classifier = KerasClassifier(build_fn = build_classifier)

In [28]:
parameters = {'batch_size': [25, 32],
              'epochs': [100, 500],
              'optimizer': ['adam' , 'rmsprop']}

In [29]:
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)

In [ ]:
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/100
6750/6750 [==============================] - 3s 404us/step - loss: 0.5694 - accuracy: 0.7963
Epoch 2/100
6750/6750 [==============================] - 2s 234us/step - loss: 0.4382 - accuracy: 0.7975
Epoch 3/100
6750/6750 [==============================] - 1s 220us/step - loss: 0.4312 - accuracy: 0.7975
Epoch 4/100
6750/6750 [==============================] - 2s 258us/step - loss: 0.4278 - accuracy: 0.7975
Epoch 5/100
6750/6750 [==============================] - 2s 269us/step - loss: 0.4253 - accuracy: 0.7975
Epoch 6/100
6750/6750 [==============================] - 2s 257us/step - loss: 0.4228 - accuracy: 0.7975
Epoch 7/100
6750/6750 [==============================] - 2s 239us/step - loss: 0.4205 - accuracy: 0.7975
Epoch 8/100
6750/6750 [==============================] - 2s 269us/step - loss: 0.4183 - accuracy: 0.8110
Epoch 9/100
6750/6750 [==============================] - 2s 270us/step - loss: 0.4173 - accuracy: 0.8219
Epoch 10/100
6750/6750 [==============================]

6750/6750 [==============================] - 2s 312us/step - loss: 0.4005 - accuracy: 0.8372
Epoch 79/100
6750/6750 [==============================] - 2s 302us/step - loss: 0.4007 - accuracy: 0.8360
Epoch 80/100
6750/6750 [==============================] - 2s 233us/step - loss: 0.4004 - accuracy: 0.8361
Epoch 81/100
6750/6750 [==============================] - 1s 210us/step - loss: 0.4004 - accuracy: 0.8357
Epoch 82/100
6750/6750 [==============================] - 2s 330us/step - loss: 0.4001 - accuracy: 0.83500s - loss: 0.4038 - accuracy
Epoch 83/100
6750/6750 [==============================] - 2s 312us/step - loss: 0.4000 - accuracy: 0.8373
Epoch 84/100
6750/6750 [==============================] - 2s 264us/step - loss: 0.4002 - accuracy: 0.8345
Epoch 85/100
6750/6750 [==============================] - 3s 374us/step - loss: 0.3999 - accuracy: 0.8361
Epoch 86/100
6750/6750 [==============================] - 3s 400us/step - loss: 0.4002 - accuracy: 0.83630s - loss: 0.3995 - accuracy: 0.

6750/6750 [==============================] - 2s 348us/step - loss: 0.3993 - accuracy: 0.8354
Epoch 55/100
6750/6750 [==============================] - 2s 334us/step - loss: 0.3986 - accuracy: 0.8364
Epoch 56/100
6750/6750 [==============================] - 2s 223us/step - loss: 0.3989 - accuracy: 0.8364
Epoch 57/100
6750/6750 [==============================] - 2s 255us/step - loss: 0.3981 - accuracy: 0.8353
Epoch 58/100
6750/6750 [==============================] - 2s 224us/step - loss: 0.3985 - accuracy: 0.8351
Epoch 59/100
6750/6750 [==============================] - 1s 216us/step - loss: 0.3979 - accuracy: 0.8354
Epoch 60/100
6750/6750 [==============================] - 2s 253us/step - loss: 0.3983 - accuracy: 0.8347
Epoch 61/100
6750/6750 [==============================] - 2s 224us/step - loss: 0.3984 - accuracy: 0.8367
Epoch 62/100
6750/6750 [==============================] - 2s 257us/step - loss: 0.3984 - accuracy: 0.8360
Epoch 63/100
6750/6750 [==============================] - 1

6750/6750 [==============================] - 3s 375us/step - loss: 0.4079 - accuracy: 0.8354
Epoch 31/100
6750/6750 [==============================] - 2s 367us/step - loss: 0.4077 - accuracy: 0.8335
Epoch 32/100
6750/6750 [==============================] - 2s 311us/step - loss: 0.4077 - accuracy: 0.8330
Epoch 33/100
6750/6750 [==============================] - 2s 296us/step - loss: 0.4073 - accuracy: 0.8338
Epoch 34/100
6750/6750 [==============================] - 2s 280us/step - loss: 0.4067 - accuracy: 0.8335
Epoch 35/100
6750/6750 [==============================] - 2s 286us/step - loss: 0.4065 - accuracy: 0.8345
Epoch 36/100
6225/6750 [==========================>...] - ETA: 0s - loss: 0.4057 - accuracy: 0.8342