In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier

### XGOR gate

In [2]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y= np.array([0,1,1,0])

In [3]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
Y

array([0, 1, 1, 0])

In [5]:
model = MLPClassifier(hidden_layer_sizes = (50 , ) , activation = 'logistic' , solver = 'adam' , max_iter = 1000 , verbose = 10)
model.fit(X , Y)

Iteration 1, loss = 0.85964222
Iteration 2, loss = 0.85209933
Iteration 3, loss = 0.84471327
Iteration 4, loss = 0.83748871
Iteration 5, loss = 0.83043016
Iteration 6, loss = 0.82354195
Iteration 7, loss = 0.81682821
Iteration 8, loss = 0.81029279
Iteration 9, loss = 0.80393932
Iteration 10, loss = 0.79777112
Iteration 11, loss = 0.79179121
Iteration 12, loss = 0.78600228
Iteration 13, loss = 0.78040669
Iteration 14, loss = 0.77500644
Iteration 15, loss = 0.76980315
Iteration 16, loss = 0.76479804
Iteration 17, loss = 0.75999190
Iteration 18, loss = 0.75538511
Iteration 19, loss = 0.75097758
Iteration 20, loss = 0.74676879
Iteration 21, loss = 0.74275772
Iteration 22, loss = 0.73894292
Iteration 23, loss = 0.73532246
Iteration 24, loss = 0.73189397
Iteration 25, loss = 0.72865461
Iteration 26, loss = 0.72560110
Iteration 27, loss = 0.72272975
Iteration 28, loss = 0.72003646
Iteration 29, loss = 0.71751673
Iteration 30, loss = 0.71516571
Iteration 31, loss = 0.71297821
Iteration 32, los

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(50,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=1000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=10, warm_start=False)

In [6]:
predict = model.predict(X)
print(predict)

[1 0 0 0]


In [7]:
print(model.score(X , Y))

0.25


### AND Gate

In [8]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y= np.array([0,0,0,1])

In [9]:
model = MLPClassifier(hidden_layer_sizes=(50,) ,activation = 'logistic',solver ='adam',max_iter=1000,verbose=10)

model.fit(X,Y)

Iteration 1, loss = 0.74406040
Iteration 2, loss = 0.73611520
Iteration 3, loss = 0.72837791
Iteration 4, loss = 0.72085223
Iteration 5, loss = 0.71354120
Iteration 6, loss = 0.70644703
Iteration 7, loss = 0.69957075
Iteration 8, loss = 0.69291195
Iteration 9, loss = 0.68646845
Iteration 10, loss = 0.68023644
Iteration 11, loss = 0.67421102
Iteration 12, loss = 0.66838708
Iteration 13, loss = 0.66276005
Iteration 14, loss = 0.65732612
Iteration 15, loss = 0.65208212
Iteration 16, loss = 0.64702528
Iteration 17, loss = 0.64215296
Iteration 18, loss = 0.63746250
Iteration 19, loss = 0.63295112
Iteration 20, loss = 0.62861582
Iteration 21, loss = 0.62445343
Iteration 22, loss = 0.62046053
Iteration 23, loss = 0.61663350
Iteration 24, loss = 0.61296851
Iteration 25, loss = 0.60946152
Iteration 26, loss = 0.60610834
Iteration 27, loss = 0.60290460
Iteration 28, loss = 0.59984583
Iteration 29, loss = 0.59692739
Iteration 30, loss = 0.59414460
Iteration 31, loss = 0.59149266
Iteration 32, los

Iteration 286, loss = 0.42830025
Iteration 287, loss = 0.42760104
Iteration 288, loss = 0.42690018
Iteration 289, loss = 0.42619766
Iteration 290, loss = 0.42549351
Iteration 291, loss = 0.42478774
Iteration 292, loss = 0.42408034
Iteration 293, loss = 0.42337134
Iteration 294, loss = 0.42266075
Iteration 295, loss = 0.42194857
Iteration 296, loss = 0.42123481
Iteration 297, loss = 0.42051950
Iteration 298, loss = 0.41980263
Iteration 299, loss = 0.41908422
Iteration 300, loss = 0.41836429
Iteration 301, loss = 0.41764284
Iteration 302, loss = 0.41691989
Iteration 303, loss = 0.41619544
Iteration 304, loss = 0.41546952
Iteration 305, loss = 0.41474213
Iteration 306, loss = 0.41401329
Iteration 307, loss = 0.41328301
Iteration 308, loss = 0.41255131
Iteration 309, loss = 0.41181819
Iteration 310, loss = 0.41108366
Iteration 311, loss = 0.41034776
Iteration 312, loss = 0.40961048
Iteration 313, loss = 0.40887184
Iteration 314, loss = 0.40813186
Iteration 315, loss = 0.40739055
Iteration 

Iteration 547, loss = 0.23274677
Iteration 548, loss = 0.23209522
Iteration 549, loss = 0.23144508
Iteration 550, loss = 0.23079635
Iteration 551, loss = 0.23014903
Iteration 552, loss = 0.22950313
Iteration 553, loss = 0.22885864
Iteration 554, loss = 0.22821558
Iteration 555, loss = 0.22757393
Iteration 556, loss = 0.22693370
Iteration 557, loss = 0.22629490
Iteration 558, loss = 0.22565752
Iteration 559, loss = 0.22502157
Iteration 560, loss = 0.22438704
Iteration 561, loss = 0.22375394
Iteration 562, loss = 0.22312227
Iteration 563, loss = 0.22249203
Iteration 564, loss = 0.22186322
Iteration 565, loss = 0.22123584
Iteration 566, loss = 0.22060990
Iteration 567, loss = 0.21998539
Iteration 568, loss = 0.21936231
Iteration 569, loss = 0.21874067
Iteration 570, loss = 0.21812047
Iteration 571, loss = 0.21750170
Iteration 572, loss = 0.21688437
Iteration 573, loss = 0.21626848
Iteration 574, loss = 0.21565403
Iteration 575, loss = 0.21504102
Iteration 576, loss = 0.21442944
Iteration 

Iteration 804, loss = 0.11051533
Iteration 805, loss = 0.11019822
Iteration 806, loss = 0.10988213
Iteration 807, loss = 0.10956706
Iteration 808, loss = 0.10925301
Iteration 809, loss = 0.10893997
Iteration 810, loss = 0.10862793
Iteration 811, loss = 0.10831691
Iteration 812, loss = 0.10800689
Iteration 813, loss = 0.10769787
Iteration 814, loss = 0.10738986
Iteration 815, loss = 0.10708284
Iteration 816, loss = 0.10677681
Iteration 817, loss = 0.10647178
Iteration 818, loss = 0.10616773
Iteration 819, loss = 0.10586467
Iteration 820, loss = 0.10556259
Iteration 821, loss = 0.10526149
Iteration 822, loss = 0.10496138
Iteration 823, loss = 0.10466223
Iteration 824, loss = 0.10436406
Iteration 825, loss = 0.10406686
Iteration 826, loss = 0.10377063
Iteration 827, loss = 0.10347536
Iteration 828, loss = 0.10318105
Iteration 829, loss = 0.10288770
Iteration 830, loss = 0.10259530
Iteration 831, loss = 0.10230386
Iteration 832, loss = 0.10201338
Iteration 833, loss = 0.10172383
Iteration 

C:\Users\Mahmudur Limon\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(50,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=1000, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=10, warm_start=False)

In [10]:
predict= model.predict(X)

print(predict)

[0 0 0 1]


In [11]:
print(model.score(X,Y))

1.0
